
language: php

php:
    - 7.2

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --no-progress
    # Used for doctrine annotations class autoloader
    - composer dumpautoload
script:
    - composer test